repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-added-large-files
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        language_version: python3 # Should be a command that runs python3.6+
        additional_dependencies: [flake8-docstrings]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint amplitude_python_sdk/
        language: system
        always_run: true
        pass_filenames: false
      - id: create requirements
        name: create requirements
        entry: poetry export -o requirements.txt
        language: system
        always_run: true
        pass_filenames: false
