# Build + upload Python package on tag pushes

trigger:
  batch: true
  branches:
    include:
    - main

pr:
  autoCancel: true
  branches:
    include:
      - main

resources:
- repo: self

variables:
  vmImageName: 'ubuntu-latest'

stages:
- stage: Test
  displayName: Testing stage
  jobs:
  - job: Validate
    displayName: Run all pre-commit hooks (linting + tests)
    pool:
      vmImage: $(vmImageName)
    strategy:
      matrix:
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'
        Python38:
          python.version: '3.8'
        Python39:
          python.version: '3.9'
    steps:
    - task: UsePythonVersion@0
      displayName: Install Python
      inputs:
        versionSpec: '$(python.version)'
    - script: |
        python -m pip install -U pip
        pip install poetry
        poetry install
      displayName: Install Poetry and dependencies
    - script: |
        poetry run pre-commit run
      displayName: Run pre-commit hooks to check linting and formatting
    - script: poetry run tox -e py
      displayName: Run tests against multiple Python versions using tox
    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: '**/test-*.xml'
        testRunTitle: 'Publish test results for Python $(python.version)'
    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
        reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'
